services:
  app:
    image: app
    ports:
    - "8080:8080"
    depends_on:
    - postgres1
  postgres1:
    image: gitpod/workspace-postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=chatdb